std = "roblox"

[rules]
divide_by_zero = "deny"
empty_if = "deny"
incorrect_standard_library_use = "deny"
shadowing = "warn"
suspicious_reverse_loop = "deny"
unscoped_variables = "deny"
unused_variable = "warn"
